title:              P-Invent
email:              pisang.invent@gmail.com
description:        Invent Stuff For You
author:             Pisang Invent
baseurl:            "/"
url:                "https://pinvent.github.io"

# Social Profiles
twitter_username:   PInvent95
github_username:    
facebook_username:  PInvent95
instagram_username:  pinvent95
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
